/**
 * Auto-initialize sqlew on server startup
 *
 * As of v5.0.6, this module handles:
 * - Cleanup of legacy CLAUDE.md injection (~/.claude/CLAUDE.md)
 * - Project .gitignore updates
 *
 * Plan mode enforcement is now handled by:
 * - UserPromptSubmit hook (on-prompt.ts) with permission_mode check
 * - PreToolUse hook (track-plan.ts) for EnterPlanMode
 * - Enhanced Skills (sqlew-decision-format, sqlew-plan-guidance)
 *
 * Skills and Hooks are managed by the sqlew-plugin (Claude Code Plugin).
 * @see https://github.com/sqlew-io/sqlew-plugin for Skills/Hooks/Agents
 */

import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { debugLog } from './utils/debug-logger.js';

/** Marker for sqlew auto-injected section in CLAUDE.md (legacy) */
const CLAUDE_MD_MARKER_START = '<!-- sqlew:auto-injected:start -->';
const CLAUDE_MD_MARKER_END = '<!-- sqlew:auto-injected:end -->';

/**
 * Escape special regex characters in a string
 */
function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Clean up legacy sqlew injection from global ~/.claude/CLAUDE.md
 *
 * As of v5.0.6, plan mode enforcement is handled by Hooks (UserPromptSubmit)
 * instead of CLAUDE.md injection. This function removes the legacy injected
 * section (between <!-- sqlew:auto-injected:start/end --> markers).
 *
 * Safe to call multiple times - does nothing if no markers found.
 */
export function cleanupGlobalClaudeMd(): void {
  const home = os.homedir();
  const claudeMdPath = path.join(home, '.claude', 'CLAUDE.md');

  // Skip if file doesn't exist
  if (!fs.existsSync(claudeMdPath)) {
    return;
  }

  const content = fs.readFileSync(claudeMdPath, 'utf-8');

  // Skip if no markers found (already clean)
  if (!content.includes(CLAUDE_MD_MARKER_START)) {
    debugLog('DEBUG', 'CLAUDE.md has no sqlew injection markers (already clean)');
    return;
  }

  // Remove the injected section
  const regex = new RegExp(
    `\\n?\\n?${escapeRegex(CLAUDE_MD_MARKER_START)}[\\s\\S]*?${escapeRegex(CLAUDE_MD_MARKER_END)}\\n?`,
    'g'
  );
  const cleaned = content.replace(regex, '').trimEnd() + '\n';

  try {
    fs.writeFileSync(claudeMdPath, cleaned, 'utf-8');
    debugLog('INFO', 'Removed legacy sqlew injection from ~/.claude/CLAUDE.md');
  } catch (error) {
    debugLog('WARN', 'Failed to clean up CLAUDE.md', { error });
  }
}

/**
 * Initialize sqlew on MCP server startup
 *
 * As of v5.0.6:
 * - Cleans up legacy CLAUDE.md injection (one-time)
 * - Updates project .gitignore
 *
 * @param projectRoot - Project root directory (for .gitignore updates)
 */
export function initializeSqlewRules(projectRoot: string): void {
  debugLog('DEBUG', 'Initializing sqlew', { projectRoot });

  // Clean up legacy CLAUDE.md injection (safe to call multiple times)
  cleanupGlobalClaudeMd();

  // Initialize .gitignore entries for sqlew-generated files
  initializeGitignore(projectRoot);
}

/**
 * Files/directories auto-generated by sqlew that should be gitignored
 *
 * As of v5.0.0:
 * - Skills and Hooks are managed by sqlew-plugin (not per-project)
 * - Gitignore is placed inside .sqlew/ directory
 *
 * Note: *.db* catches .db, .db-journal, .db-wal, .db-shm files
 */
const SQLEW_GITIGNORE_ENTRIES = [
  'queue/',
  'tmp/',
  '*.db*',
];

/** Marker comment for sqlew gitignore */
const SQLEW_GITIGNORE_MARKER = '# sqlew auto-generated files';

/**
 * Initialize .sqlew/.gitignore with sqlew auto-generated file entries
 * Creates .sqlew/.gitignore if it doesn't exist, adds missing entries if sqlew section exists
 */
export function initializeGitignore(projectRoot: string): void {
  const sqlewDir = path.join(projectRoot, '.sqlew');
  const gitignorePath = path.join(sqlewDir, '.gitignore');

  // Create .sqlew directory if needed
  if (!fs.existsSync(sqlewDir)) {
    try {
      fs.mkdirSync(sqlewDir, { recursive: true });
    } catch (error) {
      debugLog('WARN', 'Failed to create .sqlew directory', { error });
      return;
    }
  }

  // Read current .gitignore content (or empty string if doesn't exist)
  let content = '';
  if (fs.existsSync(gitignorePath)) {
    content = fs.readFileSync(gitignorePath, 'utf-8');
  } else {
    debugLog('INFO', '.sqlew/.gitignore not found, creating new file', { gitignorePath });
  }

  // Check if sqlew section already exists
  if (content.includes(SQLEW_GITIGNORE_MARKER)) {
    // Find missing entries
    const missingEntries = SQLEW_GITIGNORE_ENTRIES.filter(entry => !content.includes(entry));

    if (missingEntries.length === 0) {
      debugLog('DEBUG', 'sqlew gitignore section is up-to-date');
      return;
    }

    // Append missing entries after the marker
    try {
      const markerIndex = content.indexOf(SQLEW_GITIGNORE_MARKER);
      const afterMarker = markerIndex + SQLEW_GITIGNORE_MARKER.length;
      const newContent =
        content.slice(0, afterMarker) +
        '\n' + missingEntries.join('\n') +
        content.slice(afterMarker);
      fs.writeFileSync(gitignorePath, newContent, 'utf-8');
      debugLog('INFO', 'Added missing sqlew entries to .sqlew/.gitignore', {
        entries: missingEntries
      });
    } catch (error) {
      debugLog('WARN', 'Failed to update .sqlew/.gitignore', { error });
    }
    return;
  }

  // Build section to add (fresh install)
  const sectionLines = [
    SQLEW_GITIGNORE_MARKER,
    ...SQLEW_GITIGNORE_ENTRIES,
  ];

  // Write to .sqlew/.gitignore
  try {
    const newContent = content.trimEnd() + (content ? '\n' : '') + sectionLines.join('\n') + '\n';
    fs.writeFileSync(gitignorePath, newContent, 'utf-8');
    debugLog('INFO', 'Created .sqlew/.gitignore', {
      entries: SQLEW_GITIGNORE_ENTRIES.length
    });
  } catch (error) {
    debugLog('WARN', 'Failed to create .sqlew/.gitignore', { error });
  }
}
